service: services
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}

  deploymentBucket:
    name: ${ssm:account_code_bucket_name}
    serverSideEncryption: AES256

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:435971970349:table/IdeasTable

package:
  excludeDevDependencies: True
  exclude:
    - package.json
    - package-lock.json
    - node_modules/**
    - tests/**
  include:
    - ../shared/**
    - ../__init__.py-

functions:
  test-ideas:
    handler: test-ideas.test
    events:
      - http:
          path: /test-ideas
          method: get
          cors:
            origins:
              - "*"
            allowCredentials: true

  get-ideas:
    handler: get-ideas.handler
    events:
      - http:
          path: /ideas
          method: get
          cors:
            origins:
              - "*"
            allowCredentials: true

plugins:
  - serverless-python-requirements
